
export default {

	GET_ALL_CAMPUS : 'GET_ALL_CAMPUS',
	GET_ALL_STUDENT : 'GET_ALL_STUDENT',
	GET_ONE_CAMPUS : 'GET_ONE_CAMPUS',
	GET_ONE_STUDENT : 'GET_ONE_STUDENT',
	FORM_INPUT : 'FORM_INPUT',
	ADD_STUDENT : 'ADD_STUDENT',
	ADD_CAMPUS : 'ADD_CAMPUS',
	UPDATE_STUDENT: 'UPDATE_STUDENT',
	UPDATE_CAMPUS : 'UPDATE_CAMPUS' 
} 
